---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: silencer-leaderelection
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: silencer-leaderelection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: silencer-leaderelection
subjects:
  - kind: ServiceAccount
    name: {{ template "common.names.fullname" . }} 
