---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: silencer-leaderelection
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: silencer-leaderelection
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: silencer-leaderelection
subjects:
  - kind: ServiceAccount
    name: {{ template "common.names.fullname" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: watch-events-cluster
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: watch-events-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: watch-events-cluster
subjects:
- kind: ServiceAccount
  name: {{ template "common.names.fullname" . }} 
  namespace: {{ $.Release.Namespace }} 
